export const DOCUMENT_PAGE_CARD_HEIGHT = 138;
export const DOCUMENT_PAGE_CARD_GAP = 8;
export const DOCUMENT_PAGE_ITEM_EXTENT =
  DOCUMENT_PAGE_CARD_HEIGHT + DOCUMENT_PAGE_CARD_GAP;
export const LOCAL_PAGE_DROP_AREA_FALLBACK_HEIGHT = 72;
